### ISSUE TITLE
All applications created with boilerplate will get the same tenant id

### ISSUE THREAD

**Issue by TomasEkeli** [dolittle-boilerplates/BoundedContext.CSharp#15]
As far as I can understand the tenant will always have the same ID when someone uses the boiler-plate. This should not be.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1115616103797671/1115618459068074)

**Comment by woksin** [comment]
It should, it defaults the tenant id to what we have defined as a Development tenant in the Runtime. This should be the same across all bounded context running locally as far as I understand. cc. @einari

**Comment by einari** [comment]
This is as expected. The development tenant is the default. Closing this.
